// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgnadbzzxdmknjbmvyhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnbmFkYnp6eGRta25qYm12eWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NTE2MTEsImV4cCI6MjA1NTAyNzYxMX0.HM3_Mv-7weUOidzVELGZ2AhlnyEcx7KPOr4UjSsX0dU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);